logging:
    file:
        name: log/Sboard.log
    level:
        jdbc:
            connection: info
            hibernate: info
            resultsettable: info
            springframework:
                security: debug
            sqlonly: info
            sqltiming: info
        root: info
server:
    servlet:
        context-path: /Sboard
    port: 8181
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: Backlee99#
        url: jdbc:mysql://52.79.113.104:3306/Jboard
        username: root
    devtools:
        livereload:
            enabled: true
        restart:
            enabled: false
    jpa:
        database: mysql
        hibernate:
            ddl-auto: none
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate:
                format_sql: true
                show:
                    sql: true
                use_sql_comments: true
    security:
        user:
            name: user
            password: 1234
    thymeleaf:
        cache: false
        # prefix 설정을 안하면 HTML 수정 후 브라우저에서 새로고침 반영 안 됨 
        # 그리고 반드시 classpath 경로로 쓰고 templates 마지막에 슬래쉬(/) 붙이면 배포파일 실행안됨
        prefix: classpath:/templates

    servlet:
      multipart:
          location: src/main/resources/static/file/
          max-file-size: 10MB
